"""Add core tables (suppliers, storefronts, users, storefront_products)

Revision ID: 2a8d025246f2
Revises: a6ba16149395
Create Date: 2026-01-18 21:17:12.404849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8d025246f2'
down_revision: Union[str, None] = 'a6ba16149395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
